# fly.toml app configuration file generated for mc-server-inoonaey on 2023-05-04T21:14:37+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mc-server-inoonaey"
primary_region = "lhr"

[build]
  image = "itzg/minecraft-server:latest"

[env]
  EULA = "TRUE"

[mounts]
  destination = "/data"
  source = "mc_server_inoonaey"

[[services]]
  internal_port = 25565

  [[services.ports]]
    handlers = ["tls"]
    port = 25565

  [[services.tcp_checks]]
    grace_period = "15s"
    interval = "60s"
    restart_limit = 0
    timeout = "2s"
