# fly.toml app configuration file generated for mc-server-inoonaey on 2023-05-04T21:14:37+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mc-server-inoonaey"
primary_region = "lhr"

[build]
  image = "itzg/minecraft-server:latest"

[env]
  EULA = "TRUE"
  ENABLE_AUTOSTOP         = "TRUE"
  AUTOSTOP_TIMEOUT_EST    = 120
  AUTOSTOP_TIMEOUT_INIT   = 120
  MEMORY                  = "1G"
  AUTOSTOP_PKILL_USE_SUDO = "TRUE"

[mounts]
  destination = "/data"
  source = "mc_server_inoonaey"

[[services]]
  protocol = "tcp"
  internal_port = 25565

  [[services.ports]]
    port = 25565
