---
name: Build Minecraft App

on:
  push:
    branches:
      - main

jobs:
  build-mc-app:
    name: Build Minecraft App
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: |
          flyctl launch \
            --name mc-server \
            --copy-config
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
