---
name: Build Minecraft App

on:
  workflow_dispatch: {}

jobs:
  build-mc-app:
    name: Build Minecraft App
    runs-on: ubuntu-22.04
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Set V2 as default
        run: flyctl orgs apps-v2 default-on personal
      - name: Build app from fly.toml
        run: |
            flyctl apps create \
              --name mc-server
      - name: Add disk
        run: |
          flyctl volumes create mc_server \
          --region lhr \
          --yes
      - name: Add IP
        run: flyctl ips allocate-v4 --yes
      - name: Deploy
        run: flyctl deploy --detach
      - name: Scale Machine
        run: flyctl scale vm shared-cpu-4x --memory=2048
