---
name: Destory Minecraft App

on:
  workflow_dispatch: {}

jobs:
  destroy-mc-app:
    name: Destroy Minecraft App
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl destroy mc-server --yes
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
