---
name: Start Minecraft server

on:
  workflow_dispatch:
    inputs:
      server-name:
        description: The name of the server to run
        default: ${{ vars.DEFAULT_SERVER_NAME }}
        required: false
        type: string

jobs:
  start-mc-server:
    name: Start Minecraft Server
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: |
          flyctl launch \
            --name ${{ inputs.username }} \
            --copy-config \
            --now
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
